# config/config.yaml
server:
  port: "8080"
  host: "0.0.0.0"

crawler:
  max_workers: 1000
  queue_size: 10000
  rate_limit: 1000
  user_agent: "Crawler666/1.0"
  timeout: 30

storage:
  postgresql:
    host: "localhost"
    port: 5432
    database: "crawler666"
    username: "crawler"
    password: "crawler666"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "crawler666"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

proxy:
  enabled: true
  rotation_interval: 60
  health_check_interval: 30
  pools:
    - name: "residential"
      type: "residential"
      providers:
        - "luminati"
        - "smartproxy"
      endpoints:
        - "proxy1.example.com:8080"
        - "proxy2.example.com:8080"
    - name: "datacenter"
      type: "datacenter"
      providers:
        - "blazingseollc"
      endpoints:
        - "dc1.example.com:3128"

stealth:
  enabled: true
  fingerprint_rotation: true
  canvas_noise: true
  webgl_spoofing: true
  user_agent_rotation: true
  
